baseURL = "https://docs.myparcel.com/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
ordersectionsby = "title"
pygmentsCodeFences = true
theme = "hugo-theme-docdock"

[blackfriday]
  hrefTargetBlank = true

[params]
  disableLanguageSwitchingButton = true
  disableNavChevron = true
  themeStyle = "original"

[languages]
[languages.en]
  languageName = "English"
  title = "Documentation | MyParcel.com"
  weight = 1
[languages.nl]
  languageName = "Nederlands"
  title = "Documentatie | MyParcel.com"
  weight = 2

[[menu.shortcuts]]
  identifier = "specification"
  name = "<i class='fa fa-fw fa-file-text-o'></i> API specification"
  pre = "<h3>Links</h3>"
  url = "https://api-specification.myparcel.com"
  weight = 1

[[menu.shortcuts]]
  identifier = "github"
  name = "<i class='fa fa-fw fa-github'></i> Github"
  url = "https://github.com/MyParcelCOM"
  weight = 2

[[menu.shortcuts]]
  identifier = "website"
  name = "<i class='fa fa-fw fa-globe'></i> MyParcel.com"
  url = "https://myparcel.com"
  weight = 3

[[menu.shortcuts]]
  identifier = "contact"
  name = "<i class='fa fa-fw fa-phone'></i> Contact us"
  url = "https://myparcel.com/contact"
  weight = 4

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
