version: '3'

services:
  app:
    build:
      context: ./docker/hugo
      dockerfile: Dockerfile
      args:
        - HUGO_VERSION=$HUGO_VERSION
    image: myparcelcom/hugo:v2
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - $APP_PORT:$APP_PORT
    command: hugo server --bind 0.0.0.0 --port $APP_PORT
