version: '3'

services:
  hugo:
    build:
      context: ./docker/hugo
      dockerfile: Dockerfile
    image: myparcelcom/hugo:v5
    working_dir: /opt/hugo
    volumes:
      - .:/opt/hugo
    ports:
      - $APP_PORT:$APP_PORT
    command: hugo server --disableFastRender --bind 0.0.0.0 --port $APP_PORT
